# Logitech Attack3
axis_linear: 1  # Forward/Back
scale_linear: 0.15
scale_linear_turbo: 0.20

axis_angular: 0  # Left/Right
scale_angular: deg(30)
scale_turbo: deg(60)

enable_button: 0  # Trigger
enable_turbo_button: 1  # Button 2 aka thumb button
