# Logitech Attack3
axis_linear: 1  # Forward/Back
scale_linear: 0.2
scale_linear_turbo: 0.2

axis_angular: 0  # Left/Right
scale_angular: deg(40)
scale_turbo: deg(60)

enable_button: 0  # Trigger
enable_turbo_button: 1  # Button 2 aka thumb button
